ZOHO_CLIENT_ID = "1000.9APVQWE6W3FR5MBYEJRZ0ZB7M0IYJV"
ZOHO_CLIENT_SECRET = "f692b6ceb8f084cf06ab6ff807f0cdab41322f0ddd"
ZOHO_REFRESH_TOKEN = "1000.4f5eb84a96734f919a0c6373e2ce058c.49677e14711c5f700c7dc896e703e6ab"

# Must match your Zoho DC
ZOHO_ACCOUNTS_DOMAIN = "https://accounts.zoho.eu"
ZOHO_API_BASE = "https://www.zohoapis.eu"

# Optional. Used for download fallback.
ZOHO_WORKDRIVE_WEB_BASE = "https://workdrive.zoho.eu"
